### Пользователи
## Добавление пользователя
POST http://localhost:8080/user/registration
Content-Type: application/json

{
  "firstName": "Александр",
  "lastName": "Чесноков",
  "city": "Екатеринбург",
  "password": "65536",
  "username": "Aleks"
}

### Пользователи
## Добавление пользователя
POST http://localhost:8080/user/registration
Content-Type: application/json

{
  "firstName": "Артемий",
  "lastName": "Попов",
  "password": "123456A",
  "city": "Екатеринбург",
  "username": "Artem"
}

### Пользователи
## Добавление пользователя
POST http://localhost:8080/user/registration
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "password": "123456A",
  "city": "Екатеринбург"
}

### Пользователи
## Получение пользователя по username
GET http://localhost:8080/user/get/Artem
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

### Пользователи
## Получение всех пользователей
GET http://localhost:8080/user/all
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

### Пользователи
## Получение информации о текущем пользователе
GET http://localhost:8080/user/current
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444