### Товары
## Добавление товара
POST http://localhost:8080/product/add
Content-Type: application/json
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

{
  "name": "Дверь межкомнатная глухая массив дерева",
  "description": "межкомнатная",
  "category": "DOOR",
  "price": 3084.0,
  "countInWarehouse": 1,
  "color": "натуральный",
  "addOptions": "высота 2000, ширина 800"
}

### Товары
## Добавление товара
POST http://localhost:8080/product/add
Content-Type: application/json
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

{
  "name": "Дверь межкомнатная остекленная Лайн 2 HardFlex",
  "description": "Дверь межкомнатная Лайн 2 — конструкция с остеклением в виде продольных полос. Подходит под установку в двустворчатый проем, устанавливается на для открытия на правую или левую стороны. Изготовлена из древесины хвойных пород, не рекомендована для установки в помещениях с повышенным уровнем влажности. Покрытие гладкое, легко очищается от любых загрязнений при помощи влажной ветоши.",
  "category": "DOOR",
  "price": 3991.0,
  "countInWarehouse": 100,
  "color": "дуб тернер",
  "addOptions": "высота 2000, ширина 900"
}

### Товары
## Добавление товара
POST http://localhost:8080/product/add
Content-Type: application/json
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

{
  "name": "Дверь межкомнатная остекленная Легенда-28 полипропилен",
  "description": "Дверь межкомнатная остекленная Легенда-28 подходит для установки внутри помещений, в том числе в ванную комнату или санузел. Основной материал — МДФ. Поверхность рельефная, выполнена в цвете серое дерево. Покрытие выполнено из полипропилена (экошпон - высокая прочность), обладающего влагостойкостью. Дополнительно следует приобрести дверную коробку, ручки и наличники. При необходимости — порог, доборы, защелку.",
  "category": "DOOR",
  "price": 5426.0,
  "countInWarehouse": 100,
  "color": "серое дерево",
  "addOptions": "высота 2000, ширина 900"
}

### Товары
## Добавление товара
POST http://localhost:8080/product/add
Content-Type: application/json
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

{
  "name": "Керамогранит Artens Dina",
  "description": "Керамогранит ARTENS DINA с имитацией мрамора. Мрамор в интерьере, это очень красиво – все что создает природа смотрится очень эстетично, он не надоедает, но способен украсить что угодно. Мрамор в интерьере, это универсально - безупречно дополняет многие другие элементы дизайна и вне зависимости от стиля. Сочетание мрамора с другими текстурами и цветами действительно может улучшить общий дизайн любого помещения. Имитация мрамора, это практично и экологично - отмыть винное пятно с искусственного мраморного пола на порядок легче, а смотрится зачастую не менее эффектно. Керамогранит ARTENS DINA предназначен для облицовки поверхностей пола в гостиной. Материал получают методом формовки и обжига смеси из тугоплавких глин, кварцевого песка и воды. Плитка размером 42x42 см и толщиной 8,5 мм предназначена для эксплуатации внутри зданий и сооружений. Цвет — белый. Страна производства — Россия.",
  "category": "TILE",
  "price": 1007.0,
  "countInWarehouse": 100,
  "color": "белый",
  "addOptions": "42x42 см 1.58 м²"
}

### Товары
## Добавление товара
POST http://localhost:8080/product/add
Content-Type: application/json
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

{
  "name": "Керамогранит Alicante",
  "description": "Вес кг 27.67, Страна производства Индия, Ширина (см) 60,  Длина (см)  120,  Морозостойкость,  Да, Толщина (мм)  9,  Гарантия (лет)  0,  Назначение  Балкон, Зал, Гостиная, Терраса, Общественное помещение",
  "category": "TILE",
  "price": 2217.0,
  "countInWarehouse": 100,
  "color": "серый полированный",
  "addOptions": "60x120 см 1.44 м²"
}

### Товары
## Получение всех товаров по категории
GET http://localhost:8080/product/cat/TILE
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

### Товары
## Поиск товаров по части названия
GET http://localhost:8080/product/search/Керамогранит
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444

### Товары
## Получение все товары
GET http://localhost:8080/product/all
Cookie: JSESSIONID=DB128A5629170C9788318A8B206AC444