### Пользователи
## Добавление пользователя
POST http://localhost:8080/user/registration
Content-Type: application/json

{
  "firstName": "Александр",
  "lastName": "Чесноков",
  "city": "Екатеринбург",
  "password": "65536",
  "username": "Aleks",
  "isActive": true
}

### Пользователи
## Добавление пользователя
POST http://localhost:8080/user/registration
Content-Type: application/json

{
  "firstName": "Артемий",
  "lastName": "Попов",
  "password": "123456A",
  "username": "Artem",
  "isActive": true
}

### Пользователи
## Получение пользователя по username
GET http://localhost:8080/user/get/Artem

### Пользователи
## Получение всех пользователей
GET http://localhost:8080/user/get-all