### Заказы
## Создание заказа 1
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "userId": "1",
  "totalPrice": 16120,
  "products": [
    {
      "id": 4,
      "count": 5
    },
    {
      "id": 5,
      "count": 5
    }
  ]
}

### Заказы
## Создание заказа 2
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "userId": "2",
  "totalPrice": 10070,
  "products": [
    {
      "id": 4,
      "count": 10
    }
  ]
}

### Заказы
## Создание заказа 3
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "userId": "2",
  "totalPrice": 3084,
  "products": [
    {
      "id": 1,
      "count": 1
    }
  ]
}

### Заказы
## Получение всех заказов
GET http://localhost:8080/order/all
Content-Type: application/json

### Заказы
## Получение всех заказов пользователя по его id
GET http://localhost:8080/order/get/by-user/2
Content-Type: application/json