CREATE TABLE t_product
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    description        VARCHAR(2048),
    price              DOUBLE PRECISION,
    count_in_warehouse INTEGER,
    size               VARCHAR(255),
    color              VARCHAR(255),
    category           VARCHAR(255),
    advanced_options   VARCHAR(255),
    CONSTRAINT pk_t_product PRIMARY KEY (id)
);

CREATE TABLE "t_user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    city         VARCHAR(255),
    phone_number VARCHAR(255),
    email        VARCHAR(255),
    is_active  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE t_user_role
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

ALTER TABLE t_user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES "t_user" (id);

CREATE TABLE t_order
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number      VARCHAR(255),
    date_registration TIMESTAMP WITHOUT TIME ZONE,
    date_receipt      TIMESTAMP WITHOUT TIME ZONE,
    total_price       INTEGER,
    status            VARCHAR(255),
    user_id           BIGINT,
    CONSTRAINT pk_t_order PRIMARY KEY (id)
);

ALTER TABLE t_order
    ADD CONSTRAINT FK_T_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

CREATE TABLE order_product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT,
    product_id     BIGINT,
    count_in_order INTEGER,
    CONSTRAINT pk_order_product PRIMARY KEY (id)
);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES t_order (id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

